# Makefile generated by OpenModelica

# Simulations use -O3 by default
SIM_OR_DYNLOAD_OPT_LEVEL=
CC=gcc
CXX=g++
LINK=gcc -shared
EXEEXT=
DLLEXT=.so
CFLAGS_BASED_ON_INIT_FILE= 
CFLAGS=$(CFLAGS_BASED_ON_INIT_FILE) ${SIM_OR_DYNLOAD_OPT_LEVEL} -falign-functions -march=native -mfpmath=sse -fPIC ${MODELICAUSERCFLAGS} 
CPPFLAGS=-I"/usr/include/omc" -I. -L"/home/lapshin/work/grid/DINAMA/plugin/python/grid/tests/lc1"  -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME
LIBSIMULATIONRUNTIMEC=-lSimulationRuntimeC   -ldl
LDFLAGS=-L"/usr/lib/omc" -Wl,-rpath,'/usr/lib/omc' $(LIBSIMULATIONRUNTIMEC) -linteractive  -lexpat    -lrt -lgc -fopenmp -lsundials_kinsol -lsundials_nvecserial -llapack -lblas  -lpthread -Wl,-Bstatic -lf2c -Wl,-Bdynamic
PERL=perl
FILEPREFIX=dcmotor
MAINFILE=$(FILEPREFIX).c
MAINOBJ=$(FILEPREFIX).o
GENERATEDFILES=$(MAINFILE) $(FILEPREFIX)_functions.c $(FILEPREFIX)_functions.h $(FILEPREFIX)_records.c $(FILEPREFIX).makefile

.PHONY: omc_main_target clean bundle

# This is to make sure that dcmotor_records.c is always compiled.
.PHONY: $(FILEPREFIX)_records.c

omc_main_target: $(MAINOBJ) $(FILEPREFIX)_records.o $(FILEPREFIX)_functions.c $(FILEPREFIX)_functions.h
	$(CXX) -I. -o $(FILEPREFIX)$(EXEEXT) $(MAINOBJ) $(FILEPREFIX)_records.o $(CPPFLAGS) -L"/home/lapshin/work/grid/DINAMA/plugin/python/grid/tests/lc1"   $(CFLAGS) $(LDFLAGS)
dcmotor.conv.c: $(FILEPREFIX).c
	$(PERL) /usr/share/omc/scripts/convert_lines.pl $< $@.tmp
	@mv $@.tmp $@
	$(PERL) /usr/share/omc/scripts/convert_lines.pl $(FILEPREFIX)_functions.c $@.tmp
	@mv $@.tmp $(FILEPREFIX)_functions.c

clean:
	@rm -f $(FILEPREFIX)_records.o $(MAINOBJ)

bundle:
	@tar -cvf $(FILEPREFIX)_Files.tar $(GENERATEDFILES)