/* Simulation code for dcmotor generated by the OpenModelica Compiler 1.9.0 beta4+dev (r16888). */
#define time data->localData[0]->timeValue

/* States */
#define _$Pload$Pw(i) data->localData[i]->realVars[0]
#define $Pload$Pw _$Pload$Pw(0)
#define $P$PRE$Pload$Pw data->simulationInfo.realVarsPre[0]
#define $P$ATTRIBUTE$Pload$Pw data->modelData.realVarsData[0].attribute
#define $Pload$Pw__varInfo data->modelData.realVarsData[0].info
#define $P$PRE$Pload$Pw__varInfo data->modelData.realVarsData[0].info
#define _$Pload$Pphi(i) data->localData[i]->realVars[1]
#define $Pload$Pphi _$Pload$Pphi(0)
#define $P$PRE$Pload$Pphi data->simulationInfo.realVarsPre[1]
#define $P$ATTRIBUTE$Pload$Pphi data->modelData.realVarsData[1].attribute
#define $Pload$Pphi__varInfo data->modelData.realVarsData[1].info
#define $P$PRE$Pload$Pphi__varInfo data->modelData.realVarsData[1].info
#define _$Pinductor1$Pi(i) data->localData[i]->realVars[2]
#define $Pinductor1$Pi _$Pinductor1$Pi(0)
#define $P$PRE$Pinductor1$Pi data->simulationInfo.realVarsPre[2]
#define $P$ATTRIBUTE$Pinductor1$Pi data->modelData.realVarsData[2].attribute
#define $Pinductor1$Pi__varInfo data->modelData.realVarsData[2].info
#define $P$PRE$Pinductor1$Pi__varInfo data->modelData.realVarsData[2].info

/* StatesDerivatives */
#define _$P$DER$Pload$Pw(i) data->localData[i]->realVars[3]
#define $P$DER$Pload$Pw _$P$DER$Pload$Pw(0)
#define $P$PRE$P$DER$Pload$Pw data->simulationInfo.realVarsPre[3]
#define $P$ATTRIBUTE$P$DER$Pload$Pw data->modelData.realVarsData[3].attribute
#define $P$DER$Pload$Pw__varInfo data->modelData.realVarsData[3].info
#define $P$PRE$P$DER$Pload$Pw__varInfo data->modelData.realVarsData[3].info
#define _$P$DER$Pload$Pphi(i) data->localData[i]->realVars[4]
#define $P$DER$Pload$Pphi _$P$DER$Pload$Pphi(0)
#define $P$PRE$P$DER$Pload$Pphi data->simulationInfo.realVarsPre[4]
#define $P$ATTRIBUTE$P$DER$Pload$Pphi data->modelData.realVarsData[4].attribute
#define $P$DER$Pload$Pphi__varInfo data->modelData.realVarsData[4].info
#define $P$PRE$P$DER$Pload$Pphi__varInfo data->modelData.realVarsData[4].info
#define _$P$DER$Pinductor1$Pi(i) data->localData[i]->realVars[5]
#define $P$DER$Pinductor1$Pi _$P$DER$Pinductor1$Pi(0)
#define $P$PRE$P$DER$Pinductor1$Pi data->simulationInfo.realVarsPre[5]
#define $P$ATTRIBUTE$P$DER$Pinductor1$Pi data->modelData.realVarsData[5].attribute
#define $P$DER$Pinductor1$Pi__varInfo data->modelData.realVarsData[5].info
#define $P$PRE$P$DER$Pinductor1$Pi__varInfo data->modelData.realVarsData[5].info

/* InlineSolver Vars */

/* Algebraic Vars */
#define _$PsignalVoltage1$Pv(i) data->localData[i]->realVars[6]
#define $PsignalVoltage1$Pv _$PsignalVoltage1$Pv(0)
#define $P$PRE$PsignalVoltage1$Pv data->simulationInfo.realVarsPre[6]
#define $P$ATTRIBUTE$PsignalVoltage1$Pv data->modelData.realVarsData[6].attribute
#define $PsignalVoltage1$Pv__varInfo data->modelData.realVarsData[6].info
#define $P$PRE$PsignalVoltage1$Pv__varInfo data->modelData.realVarsData[6].info
#define _$Pload$Pa(i) data->localData[i]->realVars[7]
#define $Pload$Pa _$Pload$Pa(0)
#define $P$PRE$Pload$Pa data->simulationInfo.realVarsPre[7]
#define $P$ATTRIBUTE$Pload$Pa data->modelData.realVarsData[7].attribute
#define $Pload$Pa__varInfo data->modelData.realVarsData[7].info
#define $P$PRE$Pload$Pa__varInfo data->modelData.realVarsData[7].info
#define _$Pinductor1$Pp$Pv(i) data->localData[i]->realVars[8]
#define $Pinductor1$Pp$Pv _$Pinductor1$Pp$Pv(0)
#define $P$PRE$Pinductor1$Pp$Pv data->simulationInfo.realVarsPre[8]
#define $P$ATTRIBUTE$Pinductor1$Pp$Pv data->modelData.realVarsData[8].attribute
#define $Pinductor1$Pp$Pv__varInfo data->modelData.realVarsData[8].info
#define $P$PRE$Pinductor1$Pp$Pv__varInfo data->modelData.realVarsData[8].info
#define _$Pinductor1$Pv(i) data->localData[i]->realVars[9]
#define $Pinductor1$Pv _$Pinductor1$Pv(0)
#define $P$PRE$Pinductor1$Pv data->simulationInfo.realVarsPre[9]
#define $P$ATTRIBUTE$Pinductor1$Pv data->modelData.realVarsData[9].attribute
#define $Pinductor1$Pv__varInfo data->modelData.realVarsData[9].info
#define $P$PRE$Pinductor1$Pv__varInfo data->modelData.realVarsData[9].info
#define _$Pemf1$PinternalSupport$Ptau(i) data->localData[i]->realVars[10]
#define $Pemf1$PinternalSupport$Ptau _$Pemf1$PinternalSupport$Ptau(0)
#define $P$PRE$Pemf1$PinternalSupport$Ptau data->simulationInfo.realVarsPre[10]
#define $P$ATTRIBUTE$Pemf1$PinternalSupport$Ptau data->modelData.realVarsData[10].attribute
#define $Pemf1$PinternalSupport$Ptau__varInfo data->modelData.realVarsData[10].info
#define $P$PRE$Pemf1$PinternalSupport$Ptau__varInfo data->modelData.realVarsData[10].info
#define _$Pemf1$Pphi(i) data->localData[i]->realVars[11]
#define $Pemf1$Pphi _$Pemf1$Pphi(0)
#define $P$PRE$Pemf1$Pphi data->simulationInfo.realVarsPre[11]
#define $P$ATTRIBUTE$Pemf1$Pphi data->modelData.realVarsData[11].attribute
#define $Pemf1$Pphi__varInfo data->modelData.realVarsData[11].info
#define $P$PRE$Pemf1$Pphi__varInfo data->modelData.realVarsData[11].info
#define _$Pemf1$Pv(i) data->localData[i]->realVars[12]
#define $Pemf1$Pv _$Pemf1$Pv(0)
#define $P$PRE$Pemf1$Pv data->simulationInfo.realVarsPre[12]
#define $P$ATTRIBUTE$Pemf1$Pv data->modelData.realVarsData[12].attribute
#define $Pemf1$Pv__varInfo data->modelData.realVarsData[12].info
#define $P$PRE$Pemf1$Pv__varInfo data->modelData.realVarsData[12].info
#define _$Presistor1$PLossPower(i) data->localData[i]->realVars[13]
#define $Presistor1$PLossPower _$Presistor1$PLossPower(0)
#define $P$PRE$Presistor1$PLossPower data->simulationInfo.realVarsPre[13]
#define $P$ATTRIBUTE$Presistor1$PLossPower data->modelData.realVarsData[13].attribute
#define $Presistor1$PLossPower__varInfo data->modelData.realVarsData[13].info
#define $P$PRE$Presistor1$PLossPower__varInfo data->modelData.realVarsData[13].info
#define _$Presistor1$Pv(i) data->localData[i]->realVars[14]
#define $Presistor1$Pv _$Presistor1$Pv(0)
#define $P$PRE$Presistor1$Pv data->simulationInfo.realVarsPre[14]
#define $P$ATTRIBUTE$Presistor1$Pv data->modelData.realVarsData[14].attribute
#define $Presistor1$Pv__varInfo data->modelData.realVarsData[14].info
#define $P$PRE$Presistor1$Pv__varInfo data->modelData.realVarsData[14].info
#define _$Pground1$Pp$Pi(i) data->localData[i]->realVars[15]
#define $Pground1$Pp$Pi _$Pground1$Pp$Pi(0)
#define $P$PRE$Pground1$Pp$Pi data->simulationInfo.realVarsPre[15]
#define $P$ATTRIBUTE$Pground1$Pp$Pi data->modelData.realVarsData[15].attribute
#define $Pground1$Pp$Pi__varInfo data->modelData.realVarsData[15].info
#define $P$PRE$Pground1$Pp$Pi__varInfo data->modelData.realVarsData[15].info
#define _$Presistor1$PR_actual(i) data->localData[i]->realVars[16]
#define $Presistor1$PR_actual _$Presistor1$PR_actual(0)
#define $P$PRE$Presistor1$PR_actual data->simulationInfo.realVarsPre[16]
#define $P$ATTRIBUTE$Presistor1$PR_actual data->modelData.realVarsData[16].attribute
#define $Presistor1$PR_actual__varInfo data->modelData.realVarsData[16].info
#define $P$PRE$Presistor1$PR_actual__varInfo data->modelData.realVarsData[16].info
#define _$Pload$Pflange_b$Ptau(i) data->localData[i]->realVars[17]
#define $Pload$Pflange_b$Ptau _$Pload$Pflange_b$Ptau(0)
#define $P$PRE$Pload$Pflange_b$Ptau data->simulationInfo.realVarsPre[17]
#define $P$ATTRIBUTE$Pload$Pflange_b$Ptau data->modelData.realVarsData[17].attribute
#define $Pload$Pflange_b$Ptau__varInfo data->modelData.realVarsData[17].info
#define $P$PRE$Pload$Pflange_b$Ptau__varInfo data->modelData.realVarsData[17].info
#define _$Pground1$Pp$Pv(i) data->localData[i]->realVars[18]
#define $Pground1$Pp$Pv _$Pground1$Pp$Pv(0)
#define $P$PRE$Pground1$Pp$Pv data->simulationInfo.realVarsPre[18]
#define $P$ATTRIBUTE$Pground1$Pp$Pv data->modelData.realVarsData[18].attribute
#define $Pground1$Pp$Pv__varInfo data->modelData.realVarsData[18].info
#define $P$PRE$Pground1$Pp$Pv__varInfo data->modelData.realVarsData[18].info

/* Algebraic Parameter */
#define $Pstep1$Poffset data->simulationInfo.realParameter[0]
#define _$Pstep1$Poffset(i) $Pstep1$Poffset
#define $P$ATTRIBUTE$Pstep1$Poffset data->modelData.realParameterData[0].attribute
#define $Pstep1$Poffset__varInfo data->modelData.realParameterData[0].info
#define $Pstep1$PstartTime data->simulationInfo.realParameter[1]
#define _$Pstep1$PstartTime(i) $Pstep1$PstartTime
#define $P$ATTRIBUTE$Pstep1$PstartTime data->modelData.realParameterData[1].attribute
#define $Pstep1$PstartTime__varInfo data->modelData.realParameterData[1].info
#define $Pstep1$Pheight data->simulationInfo.realParameter[2]
#define _$Pstep1$Pheight(i) $Pstep1$Pheight
#define $P$ATTRIBUTE$Pstep1$Pheight data->modelData.realParameterData[2].attribute
#define $Pstep1$Pheight__varInfo data->modelData.realParameterData[2].info
#define $Presistor1$PT data->simulationInfo.realParameter[3]
#define _$Presistor1$PT(i) $Presistor1$PT
#define $P$ATTRIBUTE$Presistor1$PT data->modelData.realParameterData[3].attribute
#define $Presistor1$PT__varInfo data->modelData.realParameterData[3].info
#define $Presistor1$PR data->simulationInfo.realParameter[4]
#define _$Presistor1$PR(i) $Presistor1$PR
#define $P$ATTRIBUTE$Presistor1$PR data->modelData.realParameterData[4].attribute
#define $Presistor1$PR__varInfo data->modelData.realParameterData[4].info
#define $Presistor1$PT_ref data->simulationInfo.realParameter[5]
#define _$Presistor1$PT_ref(i) $Presistor1$PT_ref
#define $P$ATTRIBUTE$Presistor1$PT_ref data->modelData.realParameterData[5].attribute
#define $Presistor1$PT_ref__varInfo data->modelData.realParameterData[5].info
#define $Presistor1$Palpha data->simulationInfo.realParameter[6]
#define _$Presistor1$Palpha(i) $Presistor1$Palpha
#define $P$ATTRIBUTE$Presistor1$Palpha data->modelData.realParameterData[6].attribute
#define $Presistor1$Palpha__varInfo data->modelData.realParameterData[6].info
#define $Pemf1$Pk data->simulationInfo.realParameter[7]
#define _$Pemf1$Pk(i) $Pemf1$Pk
#define $P$ATTRIBUTE$Pemf1$Pk data->modelData.realParameterData[7].attribute
#define $Pemf1$Pk__varInfo data->modelData.realParameterData[7].info
#define $Pemf1$Pfixed$Pphi0 data->simulationInfo.realParameter[8]
#define _$Pemf1$Pfixed$Pphi0(i) $Pemf1$Pfixed$Pphi0
#define $P$ATTRIBUTE$Pemf1$Pfixed$Pphi0 data->modelData.realParameterData[8].attribute
#define $Pemf1$Pfixed$Pphi0__varInfo data->modelData.realParameterData[8].info
#define $Pinductor1$PL data->simulationInfo.realParameter[9]
#define _$Pinductor1$PL(i) $Pinductor1$PL
#define $P$ATTRIBUTE$Pinductor1$PL data->modelData.realParameterData[9].attribute
#define $Pinductor1$PL__varInfo data->modelData.realParameterData[9].info
#define $Pload$PJ data->simulationInfo.realParameter[10]
#define _$Pload$PJ(i) $Pload$PJ
#define $P$ATTRIBUTE$Pload$PJ data->modelData.realParameterData[10].attribute
#define $Pload$PJ__varInfo data->modelData.realParameterData[10].info

/* External Objects */

/* Algebraic Integer Vars */

/* Algebraic Integer Parameter */
#define $Pload$PstateSelect data->simulationInfo.integerParameter[0]
#define _$Pload$PstateSelect(i) $Pload$PstateSelect
#define $P$ATTRIBUTE$Pload$PstateSelect data->modelData.integerParameterData[0].attribute
#define $Pload$PstateSelect__varInfo data->modelData.integerParameterData[0].info

/* Algebraic Boolean Vars */

/* Algebraic Boolean Parameters */
#define $Presistor1$PuseHeatPort data->simulationInfo.booleanParameter[0]
#define _$Presistor1$PuseHeatPort(i) $Presistor1$PuseHeatPort
#define $P$ATTRIBUTE$Presistor1$PuseHeatPort data->modelData.booleanParameterData[0].attribute
#define $Presistor1$PuseHeatPort__varInfo data->modelData.booleanParameterData[0].info
#define $Pemf1$PuseSupport data->simulationInfo.booleanParameter[1]
#define _$Pemf1$PuseSupport(i) $Pemf1$PuseSupport
#define $P$ATTRIBUTE$Pemf1$PuseSupport data->modelData.booleanParameterData[1].attribute
#define $Pemf1$PuseSupport__varInfo data->modelData.booleanParameterData[1].info

/* Algebraic String Variables */

/* Algebraic String Parameter */

/* sample */

/* Jacobian Variables */
#if defined(_MSC_VER)
extern "C" {
#endif
  const int INDEX_JAC_G = 0;
  int functionJacG_column(void* data);
  int initialAnalyticJacobianG(void* data);
#if defined(_MSC_VER)
}
#endif
/* G */
/* G sparse indexes */

#if defined(_MSC_VER)
extern "C" {
#endif
  const int INDEX_JAC_A = 1;
  int functionJacA_column(void* data);
  int initialAnalyticJacobianA(void* data);
#if defined(_MSC_VER)
}
#endif
/* A */
#define $Pload$Pw$pDERA$Pload$Pw data->simulationInfo.analyticJacobians[1].seedVars[0]
#define $Pload$Pw$pDERA$Pload$Pw__varInfo dummyVAR_INFO
#define $Pload$Pphi$pDERA$Pload$Pphi data->simulationInfo.analyticJacobians[1].seedVars[1]
#define $Pload$Pphi$pDERA$Pload$Pphi__varInfo dummyVAR_INFO
#define $Pinductor1$Pi$pDERA$Pinductor1$Pi data->simulationInfo.analyticJacobians[1].seedVars[2]
#define $Pinductor1$Pi$pDERA$Pinductor1$Pi__varInfo dummyVAR_INFO
/* A sparse indexes */
#define $Pload$Pw$pDERA$indexdiff 0
#define $Pload$Pphi$pDERA$indexdiff 1
#define $Pinductor1$Pi$pDERA$indexdiff 2
#define $Pload$Pw$pDERA$indexdiffed 0
#define $Pload$Pphi$pDERA$indexdiffed 1
#define $Pinductor1$Pi$pDERA$indexdiffed 2
#if defined(_MSC_VER)
extern "C" {
#endif
  const int INDEX_JAC_B = 2;
  int functionJacB_column(void* data);
  int initialAnalyticJacobianB(void* data);
#if defined(_MSC_VER)
}
#endif
/* B */
/* B sparse indexes */

#if defined(_MSC_VER)
extern "C" {
#endif
  const int INDEX_JAC_C = 3;
  int functionJacC_column(void* data);
  int initialAnalyticJacobianC(void* data);
#if defined(_MSC_VER)
}
#endif
/* C */
/* C sparse indexes */

#if defined(_MSC_VER)
extern "C" {
#endif
  const int INDEX_JAC_D = 4;
  int functionJacD_column(void* data);
  int initialAnalyticJacobianD(void* data);
#if defined(_MSC_VER)
}
#endif
/* D */
/* D sparse indexes */


