from Solver import *

class SHTERM (Solver):
	def __init__ (self, rnglist, 
			save 	= default,   
			end 	= default,    
			out 	= default,    
			smax 	= default,   
			smin 	= default,
			drlti 	= default,  
			dabsi 	= default,  
			drltu 	= default,  
			dabsu 	= default,  
			drltx 	= default,
			dabsx 	= default,  
			flag 	= default,   
			itr 	= default,    
			debug 	= default,  
			optim 	= default,
			control 	= default, 
			mode 	= default,   
			change 	= default,
			outs 	= default,   
			predict 	= default, 
			scheme 	= default, 
			weight 	= default, 
			second 	= default,
			ignore 	= default,
			atm 	= default,
			scale 	= default,  
			checkm 	= default, 
			outper 	= default, 
			outvar 	= default,	
			prttime = default,
			rlmin 	= default,  
			msheps 	= default, 
			parerr 	= default, 
			pspprt 	= default, 
			err 	= default, 
			desc=default):
		self.this = Solver ("SHTERM", rnglist,
			save,   
			end,    
			out,
			smax,
			smin,
			drlti,  
			dabsi,  
			drltu,  
			dabsu,
			drltx,
			dabsx,  
			flag,   
			itr,    
			debug,  
			optim,
			control, 
			mode,   
			change,
			outs,   
			predict, 
			scheme, 
			weight, 
			second,
			ignore,
			atm,
			scale,  
			checkm, 
			outper, 
			outvar,	
			prttime,
			rlmin,  
			msheps, 
			parerr, 
			pspprt, 
			err,desc)
